INCLUDE += -I../../src/Proxy -I../../src/TarsComm -I./MockClass -I../../src/Router -I../../src/Comm -I../../src/KVCacheServer -I../../src/MKVCacheServer -I../../src/MKVCacheServer/jmem_multi_hashmap_malloc

INCLUDE    += -I../../src/Router -I../../src/DbAccess -I../../src/ConfigServer -I../../src/PropertyServer

LIB += -L../../src/lib -lcache_comm

include ../makefile.inc


